# Generated by Django 5.1 on 2024-09-24 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Habitacion',
            fields=[
                ('cod_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_categoria', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('cod_hotel', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('cod_habitacion', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_general', models.CharField(max_length=300)),
                ('capacidad', models.IntegerField()),
                ('piso', models.IntegerField()),
                ('equipamiento', models.CharField(max_length=300)),
                ('img1_habitacion', models.ImageField(null=True, upload_to='habitaciones')),
                ('img2_habitacion', models.ImageField(null=True, upload_to='habitaciones')),
                ('img3_habitacion', models.ImageField(null=True, upload_to='habitaciones')),
                ('cod_categoria', models.ForeignKey(db_column='cod_categoria', on_delete=django.db.models.deletion.CASCADE, to='core.categoria_habitacion')),
                ('cod_hotel', models.ForeignKey(db_column='cod_hotel', on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('cod_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('cantidad_personas', models.IntegerField()),
                ('cod_habitacion', models.ForeignKey(db_column='cod_habitacion', on_delete=django.db.models.deletion.CASCADE, to='core.habitacion')),
                ('rut', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente'), ('empleado', 'Empleado')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
