# Generated by Django 5.1 on 2024-09-05 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Habitacion',
            fields=[
                ('cod_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_categoria', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('cod_hotel', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('cod_habitacion', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_general', models.CharField(max_length=300)),
                ('capacidad', models.IntegerField()),
                ('piso', models.IntegerField()),
                ('equipamiento', models.CharField(max_length=300)),
                ('img1_habitacion', models.ImageField(null=True, upload_to='habitaciones')),
                ('img2_habitacion', models.ImageField(null=True, upload_to='habitaciones')),
                ('img3_habitacion', models.ImageField(null=True, upload_to='habitaciones')),
                ('cod_categoria', models.ForeignKey(db_column='cod_categoria', on_delete=django.db.models.deletion.CASCADE, to='core.categoria_habitacion')),
                ('cod_hotel', models.ForeignKey(db_column='cod_hotel', on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
            ],
        ),
    ]
