# Generated by Django 5.1 on 2024-09-05 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_habitacion_hotel_habitacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('cod_reserva', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('cantidad_personas', models.IntegerField()),
                ('cod_habitacion', models.ForeignKey(db_column='cod_habitacion', on_delete=django.db.models.deletion.CASCADE, to='core.habitacion')),
                ('rut', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
